### ISSUE TITLE
Changes for user manual v1.2.2

### ISSUE THREAD

**Issue by giahung24** [tschaffter/jmod#1]
Hello,
I am reading your User Manual and in the section 4.6 Modularity detection, the example code seems to be of the old version:

modSettings settings = JmodSettings.getInstance();
settings.setUseNewman(true); 

In the your current version, there is not this method "setUserNewman()". So I ignored this line and continued running the code. Will it run correctly?
Hope to receive your help soon!
Thank you.

**Comment by tschaffter** [comment]
Yes, a new version of Jmod has been released since then.

To enable Newman's algorithm:

JmodSettings.getInstance().setModularityDetectionMethod(String[] methods);

where methods is a String array which contains a list of method identifiers. The identifier of Newman's method is "Newman". You can find all the methods available here:

https://github.com/tschaffter/jmod/tree/master/src/main/java/ch/epfl/lis/jmod/modularity/community/dividers

For more information:

https://github.com/tschaffter/jmod/blob/master/src/main/java/ch/epfl/lis/jmod/JmodSettings.java
https://github.com/tschaffter/jmod/blob/master/src/main/java/ch/epfl/lis/jmod/modularity/community/dividers/CommunityDividerManager.java

Best,

Thomas
